const SAMPLE_CARD_TEMPLATES = [
  {
    cardNumber1: "U",
    card_type_name: "UNIT",
    name:
      "\u30ac\u30f3\u30c0\u30e0TR-1[\u30d8\u30a4\u30ba\u30eb\u30fb\u30a2\u30a6\u30b9\u30e9](\u30ae\u30ac\u30f3\u30c6\u30a3\u30c3\u30af\u30fb\u30a2\u30fc\u30e0\u30fb\u30e6\u30cb\u30c3\u30c8\u88c5\u5099)",
    modelNumber1: "RX-121-2A",
    sp_power_color1_name: "\u9752",
    spPowerCost1: "3",
    totalCost: "5",
    resourceCost: "2",
    text_normal:
      "\u30ec\u30a4\u30a2\u30a6\u30c8\u78ba\u8a8d\u7528\u306e\u9577\u3081\u306e\u30b5\u30f3\u30d7\u30eb\u30ab\u30fc\u30c9\u3067\u3059\u3002",
    melee1: "3",
    shooting1: "2",
    defense1: "3",
    space: 1,
    earth: 1,
    traits: ["TR", "\u30b5\u30f3\u30d7\u30eb"],
    traits2: ["\u30e2\u30d3\u30eb\u30b9\u30fc\u30c4"],
    setName: "Sample Set U",
  },
  {
    cardNumber1: "C",
    card_type_name: "COMMAND",
    name: "Sample Tactics",
    modelNumber1: "",
    sp_power_color1_name: "\u8d64",
    spPowerCost1: "2",
    totalCost: "2",
    resourceCost: "1",
    text_normal: "Sample command text for pagination and layout checks.",
    melee1: "",
    shooting1: "",
    defense1: "",
    space: 0,
    earth: 0,
    traits: ["Tactics"],
    traits2: [],
    setName: "Sample Set C",
  },
  {
    cardNumber1: "CH",
    card_type_name: "CHARACTER",
    name: "Sample Pilot",
    modelNumber1: "",
    sp_power_color1_name: "\u7dd1",
    spPowerCost1: "1",
    totalCost: "2",
    resourceCost: "1",
    text_normal: "Sample character text for deck builder testing.",
    melee1: "1",
    shooting1: "1",
    defense1: "1",
    space: 1,
    earth: 0,
    traits: ["Pilot"],
    traits2: ["Sample Team"],
    setName: "Sample Set CH",
  },
  {
    cardNumber1: "O",
    card_type_name: "OPERATION",
    name: "Sample Operation",
    modelNumber1: "",
    sp_power_color1_name: "\u9ed2",
    spPowerCost1: "4",
    totalCost: "4",
    resourceCost: "1",
    text_normal: "Sample operation effect shown in the search result layout.",
    melee1: "",
    shooting1: "",
    defense1: "",
    space: 0,
    earth: 0,
    traits: ["Operation"],
    traits2: [],
    setName: "Sample Set O",
  },
  {
    cardNumber1: "G",
    card_type_name: "GENERATION",
    name: "Sample Generation",
    modelNumber1: "",
    sp_power_color1_name: "\u767d",
    spPowerCost1: "0",
    totalCost: "0",
    resourceCost: "0",
    text_normal: "Sample generation card for list density checks.",
    melee1: "",
    shooting1: "",
    defense1: "",
    space: 0,
    earth: 0,
    traits: ["Generation"],
    traits2: [],
    setName: "Sample Set G",
  },
  {
    cardNumber1: "A",
    card_type_name: "ACE",
    name: "Sample Ace",
    modelNumber1: "",
    sp_power_color1_name: "\u7d2b",
    spPowerCost1: "5",
    totalCost: "6",
    resourceCost: "2",
    text_normal: "Sample ace card for image-only and detail-mode checks.",
    melee1: "4",
    shooting1: "4",
    defense1: "4",
    space: 1,
    earth: 1,
    traits: ["Ace"],
    traits2: ["Sample Corps"],
    setName: "Sample Set A",
  },
];

function createSampleCard(index) {
  const template = SAMPLE_CARD_TEMPLATES[index % SAMPLE_CARD_TEMPLATES.length];
  const number = String(index + 1).padStart(3, "0");
  const needsSuffix = index >= SAMPLE_CARD_TEMPLATES.length;
  const suffix = needsSuffix ? ` ${Math.floor(index / SAMPLE_CARD_TEMPLATES.length) + 1}` : "";

  return {
    cardId: `sample-${template.cardNumber1.toLowerCase()}-${number}`,
    cardNumber1: template.cardNumber1,
    cardNumber2: number,
    card_type_name: template.card_type_name,
    name: `${template.name}${suffix}`,
    modelNumber1: template.modelNumber1,
    modelNumber2: "",
    sp_power_color1_name: template.sp_power_color1_name,
    spPowerCost1: template.spPowerCost1,
    sp_power_color2_name: "",
    spPowerCost2: "",
    totalCost: template.totalCost,
    resourceCost: template.resourceCost,
    text_normal: template.text_normal,
    melee1: template.melee1,
    melee2: "",
    shooting1: template.shooting1,
    shooting2: "",
    defense1: template.defense1,
    defense2: "",
    space: template.space,
    earth: template.earth,
    traits: template.traits,
    traits2: template.traits2,
    sets: [`${template.setName} ${Math.floor(index / SAMPLE_CARD_TEMPLATES.length) + 1}`],
    aliases: "",
    exclusivePilots: "",
    altName: "",
  };
}

export const MOCK_DECK_SEARCH_RESULTS = Array.from({ length: 60 }, (_, index) =>
  createSampleCard(index)
);
